/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import helper.XDate;
import java.awt.Color;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Random;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import java.util.Timer;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import model.DonHang;
import model.DonHangChiTiet;
import model.KhachHang;
import model.KhuyenMai;
import model.SanPham;
import model.SanPhamChiTiet;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.Auth;
import service.DonHangService;
import service.DonViTinh_service;
import service.KhachHangService;
import service.KhuyenMaiService;
import service.SanPhamChiTietService;

/**
 *
 * @author phungvantung
 */
public class BanHang_JPanel extends javax.swing.JPanel implements Runnable, ThreadFactory {

    /**
     * Creates new form BanHang_JPanel
     */
    private WebcamPanel panel = null;
    private Webcam webcam = null;
    private static final long serialVersionUID = 6441489157408381878L;
    private Executor executor = Executors.newSingleThreadExecutor(this);

    SanPhamChiTietService sanPhamChiTietService = new SanPhamChiTietService();
    DonViTinh_service donViTinhService = new DonViTinh_service();
    DonHangService donHangService = new DonHangService();
    KhuyenMaiService khuyenMaiService = new KhuyenMaiService();
    KhachHangService khachHangService = new KhachHangService();

    ArrayList<SanPhamChiTiet> spctlist = new ArrayList<>();
    ArrayList<DonHang> dhlist = new ArrayList<>();
    ArrayList<DonHangChiTiet> dhctlist = new ArrayList<>();
    ArrayList<KhuyenMai> kmlist = new ArrayList<>();

    DefaultTableModel spctmodel = new DefaultTableModel();
    DefaultTableModel dhmodel = new DefaultTableModel();
    DefaultTableModel dhctmodel = new DefaultTableModel();

    int page = 1, index = -1, maDH = -1;
    String ten = "";
    float phiShip = 0, tienGiam = 0, tongTien = 0;
    int trangThai = 0, loaiDonHang = 0;

    DecimalFormat decimalFormat = new DecimalFormat("#,### VND");
    DonHangChiTiet dhct;
    SanPhamChiTiet spct;
    DonHang dh;
    KhuyenMai km;

    public BanHang_JPanel() {
        initComponents();
        initWebcam();
        dongHo();
        this.setBackground(new Color(37, 108, 205));
        spctmodel = (DefaultTableModel) tbl_sp.getModel();
        dhmodel = (DefaultTableModel) tbl_dh.getModel();
        dhctmodel = (DefaultTableModel) tbl_dhct.getModel();
        loadDataToSP();
        loadDataToDH();
        txt_diem.setEnabled(false);
    }

    private void initWebcam() {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0); //0 is default webcam
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);

        qrcode.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 120));

        executor.execute((Runnable) this);

    }

    public void sclose() {
        webcam.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        checkbox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_dhct = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        ThanhToan = new javax.swing.JTabbedPane();
        panelhd = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txt_manv = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        txt_hoten = new javax.swing.JTextField();
        txt_diem = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_diaChi = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txt_tienhang = new javax.swing.JLabel();
        cbo_httt = new javax.swing.JComboBox<>();
        txt_khachtra = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txt_tralai = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        lbldongho = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt_giaGiam = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txt_tongtien = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txt_phiship = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        btn_thanhToan = new javax.swing.JButton();
        thanhToanDatHang = new javax.swing.JCheckBox();
        btn_giaoHang = new javax.swing.JButton();
        btn_hoanThanh = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        btn_huy1 = new javax.swing.JButton();
        qrcode = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt_tk = new javax.swing.JTextField();
        phanTrang = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sp = new javax.swing.JTable();
        jButton18 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_dh = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbo_trangThai = new javax.swing.JComboBox<>();
        cbo_loaiDH = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(37, 108, 205));
        setPreferredSize(new java.awt.Dimension(1500, 820));

        jPanel2.setBackground(new java.awt.Color(172, 214, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14))); // NOI18N

        checkbox.setBackground(new java.awt.Color(0, 0, 0));
        checkbox.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        checkbox.setText("Đặt hàng");

        jButton1.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jButton1.setText("Làm mới giỏ hàng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jButton2.setText("Tạo đơn hàng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jButton3.setText("Bỏ khỏi giỏ hàng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jButton4.setText("Quét mã");

        tbl_dhct.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        tbl_dhct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "ĐVT", "Khối lượng", "Đơn giá", "Giá giảm", "Số lượng", "Thành tiền"
            }
        ));
        tbl_dhct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dhctMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbl_dhct);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(checkbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkbox)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)))
        );

        jPanel3.setBackground(new java.awt.Color(172, 214, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Điền thông tin đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14))); // NOI18N

        ThanhToan.setBackground(new java.awt.Color(172, 214, 255));

        panelhd.setBackground(new java.awt.Color(172, 214, 255));

        jPanel13.setBackground(new java.awt.Color(172, 214, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chung", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel29.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel29.setText("Mã nhân viên");

        jLabel31.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel31.setText("Số điện thoại ");

        jLabel32.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel32.setText("Họ tên khách hàng");

        jLabel33.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel33.setText("Điểm thân thiết");

        txt_manv.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        txt_manv.setForeground(new java.awt.Color(0, 0, 204));
        txt_manv.setText("NV00001");

        txt_sdt.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        txt_hoten.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N

        txt_diem.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        txt_diem.setText("0");
        txt_diem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diemActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jButton9.setText("Chon");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jButton10.setText("Dùng");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel34.setText("Địa chỉ");

        txt_diaChi.setColumns(20);
        txt_diaChi.setRows(5);
        jScrollPane7.setViewportView(txt_diaChi);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(txt_manv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(101, 101, 101))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_diem, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel13Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel29, jLabel31, jLabel32, jLabel33});

        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(5, 5, 5)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_diem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(5, 5, 5)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel14.setBackground(new java.awt.Color(172, 214, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel36.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel36.setText("Tổng tiền hàng");

        jLabel40.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel40.setText("Hình thức thanh toán");

        jLabel42.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel42.setText("Khách trả");

        txt_tienhang.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        txt_tienhang.setForeground(new java.awt.Color(204, 0, 0));
        txt_tienhang.setText("0");
        txt_tienhang.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_tienhangInputMethodTextChanged(evt);
            }
        });

        cbo_httt.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        cbo_httt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Chuyển khoản" }));

        txt_khachtra.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        txt_khachtra.setForeground(new java.awt.Color(0, 0, 255));
        txt_khachtra.setText("0");
        txt_khachtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_khachtraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_khachtraMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_khachtraMouseReleased(evt);
            }
        });
        txt_khachtra.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_khachtraInputMethodTextChanged(evt);
            }
        });
        txt_khachtra.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_khachtraPropertyChange(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel43.setText("Trả lại");

        txt_tralai.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        txt_tralai.setForeground(new java.awt.Color(204, 0, 0));
        txt_tralai.setText("0");

        jLabel50.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel50.setText("Thời gian");

        lbldongho.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        lbldongho.setForeground(new java.awt.Color(204, 0, 0));
        lbldongho.setText("32:01:34 A 32/3/2343");

        jLabel37.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel37.setText("Tiền giảm");

        txt_giaGiam.setText("0");
        txt_giaGiam.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_giaGiamInputMethodTextChanged(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel38.setText("Tổng Tiển");

        txt_tongtien.setText("0");

        jLabel39.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jLabel39.setText("Phí ship");

        txt_phiship.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        txt_phiship.setText("0");
        txt_phiship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_phishipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_phishipMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_phishipMouseReleased(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        jButton11.setText("Chọn");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tienhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(lbldongho, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(txt_phiship)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tralai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_httt, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(txt_khachtra, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txt_tongtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txt_giaGiam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(lbldongho))
                .addGap(5, 5, 5)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txt_tienhang))
                .addGap(5, 5, 5)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txt_phiship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txt_giaGiam))
                .addGap(5, 5, 5)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txt_tongtien))
                .addGap(5, 5, 5)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(cbo_httt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txt_khachtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addGap(4, 4, 4)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(txt_tralai))
                .addGap(134, 134, 134))
        );

        btn_thanhToan.setBackground(new java.awt.Color(230, 244, 241));
        btn_thanhToan.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btn_thanhToan.setText("Thanh toán");
        btn_thanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhToanActionPerformed(evt);
            }
        });

        thanhToanDatHang.setText("Thanh toán");

        btn_giaoHang.setBackground(new java.awt.Color(230, 244, 241));
        btn_giaoHang.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btn_giaoHang.setText("Giao hàng");
        btn_giaoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giaoHangActionPerformed(evt);
            }
        });

        btn_hoanThanh.setBackground(new java.awt.Color(230, 244, 241));
        btn_hoanThanh.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btn_hoanThanh.setText("Hoàn thành");
        btn_hoanThanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoanThanhActionPerformed(evt);
            }
        });

        btn_huy.setBackground(new java.awt.Color(230, 244, 241));
        btn_huy.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        btn_huy1.setBackground(new java.awt.Color(230, 244, 241));
        btn_huy1.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        btn_huy1.setText("Chờ thanh toán");
        btn_huy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huy1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelhdLayout = new javax.swing.GroupLayout(panelhd);
        panelhd.setLayout(panelhdLayout);
        panelhdLayout.setHorizontalGroup(
            panelhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhdLayout.createSequentialGroup()
                .addGroup(panelhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelhdLayout.createSequentialGroup()
                        .addGroup(panelhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 339, Short.MAX_VALUE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 339, Short.MAX_VALUE)
                            .addGroup(panelhdLayout.createSequentialGroup()
                                .addGroup(panelhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_hoanThanh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_thanhToan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_giaoHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_huy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelhdLayout.createSequentialGroup()
                        .addComponent(thanhToanDatHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_huy1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelhdLayout.setVerticalGroup(
            panelhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thanhToanDatHang)
                    .addComponent(btn_huy1))
                .addGap(4, 4, 4)
                .addGroup(panelhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_thanhToan)
                    .addComponent(btn_giaoHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelhdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hoanThanh)
                    .addComponent(btn_huy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ThanhToan.addTab("Hóa đơn", panelhd);

        qrcode.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 342, Short.MAX_VALUE)
            .addComponent(qrcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(qrcode, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(172, 214, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14))); // NOI18N

        txt_tk.setFont(new java.awt.Font("DialogInput", 0, 10)); // NOI18N

        phanTrang.setBackground(new java.awt.Color(0, 0, 0));
        phanTrang.setFont(new java.awt.Font("DialogInput", 0, 10)); // NOI18N
        phanTrang.setText("1");

        jButton5.setFont(new java.awt.Font("DialogInput", 0, 10)); // NOI18N
        jButton5.setText("Tìm kiếm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText(">>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbl_sp.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        tbl_sp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ma SPCT", "Tên SP", "ĐVT", "Khối lượng", "Đơn giá", "Số lượng", "Khuyến mãi", "Giá giảm"
            }
        ));
        tbl_sp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_spMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sp);
        if (tbl_sp.getColumnModel().getColumnCount() > 0) {
            tbl_sp.getColumnModel().getColumn(0).setMinWidth(60);
            tbl_sp.getColumnModel().getColumn(0).setMaxWidth(60);
            tbl_sp.getColumnModel().getColumn(1).setMinWidth(100);
        }

        jButton18.setText("Mới");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_tk, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(phanTrang)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(txt_tk)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton18))
                        .addComponent(phanTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel5.setBackground(new java.awt.Color(172, 214, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách đơn hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14))); // NOI18N

        tbl_dh.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        tbl_dh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã nhân viên", "Tổng tiền", "Loại DH", "Trạng thái"
            }
        ));
        tbl_dh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dhMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_dh);
        if (tbl_dh.getColumnModel().getColumnCount() > 0) {
            tbl_dh.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel2.setText("Trạng thái");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel3.setText("Loại hóa đơn");

        cbo_trangThai.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        cbo_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã thanh toán", "Chờ thanh toán" }));
        cbo_trangThai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_trangThaiItemStateChanged(evt);
            }
        });
        cbo_trangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trangThaiActionPerformed(evt);
            }
        });

        cbo_loaiDH.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        cbo_loaiDH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang giao hàng" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbo_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbo_loaiDH, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbo_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbo_loaiDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_diemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diemActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        newForm();
        trangThai = 0;
        loaiDonHang = 0;
        loadDataToSP();
        loadDataToDH();
        maDH = -1;
        ten = "";
    }//GEN-LAST:event_jButton18ActionPerformed

    private void tbl_dhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dhMouseClicked
        // TODO add your handling code here:
        index = tbl_dh.getSelectedRow();
        dh = dhlist.get(index);
        maDH = dh.getMaDonHang();
        loadDataToDHCT(maDH);
        showFormDH();
    }//GEN-LAST:event_tbl_dhMouseClicked

    public void showFormDH() {
        txt_manv.setText(dh.getMaNhanVien());
        DecimalFormat decimalFormat = new DecimalFormat("#,### VND");
        String formattedAmount = decimalFormat.format(dh.getTienHang());
        txt_tienhang.setText(formattedAmount);
        formattedAmount = decimalFormat.format(dh.getTienGiam());
        txt_giaGiam.setText(formattedAmount);
        formattedAmount = decimalFormat.format(dh.getPhiKhac());
        txt_phiship.setText(formattedAmount);
        txt_sdt.setText(dh.getDienThoai());
        txt_diaChi.setText(dh.getDiaChi());
        formattedAmount = decimalFormat.format(dh.getTongTien());
        txt_tongtien.setText(formattedAmount);
        cbo_httt.setSelectedItem(dh.getMaHHTT() == 1 ? "Tiền mặt" : "Chuyển khoản");
        System.out.println(dh.isLoaiDonHang());
        if (dh.isLoaiDonHang() == 4) {
            txt_diaChi.setEnabled(false);
            txt_phiship.setEnabled(false);
            btn_giaoHang.setEnabled(false);
            btn_hoanThanh.setEnabled(false);
            btn_huy.setEnabled(false);
            btn_thanhToan.setEnabled(true);
            txt_khachtra.setEnabled(true);
            cbo_httt.setEnabled(true);
            
        } else {
            cbo_httt.setSelectedItem("Chuyển khoản");
            cbo_httt.setEnabled(false);
            txt_diaChi.setEnabled(true);
            txt_phiship.setEnabled(true);
            btn_giaoHang.setEnabled(true);
            btn_hoanThanh.setEnabled(true);
            btn_huy.setEnabled(true);
            btn_thanhToan.setEnabled(false);
            txt_khachtra.setEnabled(false);
        }

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DonHang dh = new DonHang();
        dh.setMaNhanVien(Auth.user.getMaNhanVien());
        dh.setTrangThai(0);
        dh.setNgayTao(XDate.toString(XDate.now(), "dd-MM-yyyy"));
        dh.setTienHang(0);
        if (checkbox.isSelected()) {
            dh.setLoaiDonHang(0);
        } else {
            dh.setLoaiDonHang(4);
        }
        Integer rs = donHangService.insertDH(dh);
        if (rs != null) {
            JOptionPane.showMessageDialog(null, "Tạo đơn hàng thành công");
            loadDataToDH();
        } else {
            JOptionPane.showMessageDialog(null, "Tạo đơn hàng thất bại");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbl_spMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_spMouseClicked
        // TODO add your handling code here:
        index = tbl_sp.getSelectedRow();
        spct = spctlist.get(index);
        km = kmlist.get(index);
        if (maDH == -1) {
            JOptionPane.showMessageDialog(null, "Mời chọn đơn hàng");
            return;
        }
        themSPtoDHCT();
    }//GEN-LAST:event_tbl_spMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa chứ");
        if (chon != 0) {
            return;
        }
        Integer kq = donHangService.deleteDHCT(dhct.getMaDonHangChiTiet());
        int sl = dhct.getSoLuong();
        SanPhamChiTiet spct = sanPhamChiTietService.searchByIdSPCT(dhct.getMaSanPhamChiTiet());
        spct.setSoLuong(spct.getSoLuong() + sl);
        if (kq != null) {
            JOptionPane.showMessageDialog(null, "Bỏ thành công");
            loadDataToDHCT(maDH);
            donHangService.updateDH(dh);
            loadDataToDH();
            SanPham sp = new SanPham();
            sanPhamChiTietService.updateSPCT(sp, spct);
            loadDataToSP();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbl_dhctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dhctMouseClicked
        // TODO add your handling code here:
        index = tbl_dhct.getSelectedRow();
        dhct = dhctlist.get(index);
    }//GEN-LAST:event_tbl_dhctMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        donHangService.updateDH(dh);
        loadDataToDH();
        for (DonHangChiTiet dhct : dhctlist) {
            SanPhamChiTiet spct = sanPhamChiTietService.searchByIdSPCT(dhct.getMaSanPhamChiTiet());
            spct.setSoLuong(spct.getSoLuong() + dhct.getSoLuong());
            SanPham sp = new SanPham();
            sanPhamChiTietService.updateSPCT(sp, spct);
        }
        loadDataToSP();
        donHangService.deleteAllDHCT(maDH);
        loadDataToDHCT(maDH);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        sclose();
        ArrayList<KhachHang> khs = khachHangService.paging(1, 1, txt_sdt.getText(), "");
        if (khs.size() != 0) {
            KhachHang kh = khs.get(0);
            txt_hoten.setText(kh.getTenKhachHang());
            txt_diem.setText(String.valueOf(kh.getDiem()));
            dh.setMaKhachHang(kh.getMaKhachHang());
        } else {
            txt_hoten.setText("Khách vãng lai");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        thanhToan();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txt_khachtraInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_khachtraInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_khachtraInputMethodTextChanged

    private void btn_thanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhToanActionPerformed
        // TODO add your handling code here:
        if(dhctlist.size()==0){
            JOptionPane.showMessageDialog(null, "Mời chọn sản phẩm");
            return;
        }
        readForm();
        dh.setTrangThai(1);
        Integer rs = donHangService.updateDH(dh);
        if (rs != null) {
            exportExcel(dhctlist);
            JOptionPane.showMessageDialog(null, "Thanh toán thành công");
            loadDataToDH();
            maDH=0;
            loadDataToDHCT(maDH);
            tichDiem();
            newForm();
        } else {
            JOptionPane.showMessageDialog(null, "Thanh toán thất bại");
        }
        
    }//GEN-LAST:event_btn_thanhToanActionPerformed

    private void txt_khachtraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_khachtraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_khachtraMouseExited

    private void btn_giaoHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giaoHangActionPerformed
        // TODO add your handling code here:
        if(txt_diaChi.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Địa chỉ không được để trống");
            return;
        }
        readForm();
        if (thanhToanDatHang.isSelected()) {
            dh.setTrangThai(1);
        } else {
            dh.setTrangThai(0);
        }
        dh.setLoaiDonHang(1);
        Integer rs = donHangService.updateDH(dh);
        if (rs != null) {
            JOptionPane.showMessageDialog(null, "Đặt hàng thành công");
            loadDataToDH();
            tichDiem();
            newForm();
            dhctmodel.setRowCount(0);
        } else {
            JOptionPane.showMessageDialog(null, "Đặt hàng thất bại");
        }
    }//GEN-LAST:event_btn_giaoHangActionPerformed

    private void btn_hoanThanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoanThanhActionPerformed
        // TODO add your handling code here:
        dh.setTrangThai(1);
        dh.setLoaiDonHang(2);
        Integer rs = donHangService.updateDH(dh);
        if (rs != null) {
            JOptionPane.showMessageDialog(null, "Hoàn thành đơn hàng");
            loadDataToDH();
            tichDiem();
            newForm();
            dhctmodel.setRowCount(0);
        } else {
            JOptionPane.showMessageDialog(null, "Đon hàng thất bại");
        }
    }//GEN-LAST:event_btn_hoanThanhActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        dh.setLoaiDonHang(3);
        Integer rs = donHangService.updateDH(dh);
        if (rs != null) {
            JOptionPane.showMessageDialog(null, "Hủy đơn hàng thành công");
            loadDataToDH();
            newForm();
        } else {
            JOptionPane.showMessageDialog(null, "Hủy đơn hàng thất bại");
        }
    }//GEN-LAST:event_btn_huyActionPerformed

    private void txt_tienhangInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_tienhangInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_tienhangInputMethodTextChanged

    private void txt_giaGiamInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_giaGiamInputMethodTextChanged
        // TODO add your handling code here:
        System.out.println("thây đổi");
    }//GEN-LAST:event_txt_giaGiamInputMethodTextChanged

    private void txt_phishipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_phishipMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phishipMouseExited

    private void txt_khachtraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_khachtraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_khachtraMouseEntered

    private void txt_khachtraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_khachtraPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_khachtraPropertyChange

    private void txt_phishipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_phishipMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phishipMouseEntered

    private void txt_phishipMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_phishipMouseReleased
        // TODO add your handling code here:
        phiShip = Float.valueOf(txt_phiship.getText());
        tongTien = phiShip + dh.getTongTien() - tienGiam;
        String formattedAmount = decimalFormat.format(tongTien);
        txt_tongtien.setText(formattedAmount);
    }//GEN-LAST:event_txt_phishipMouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ten = txt_tk.getText();
        loadDataToSP();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cbo_trangThaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_trangThaiItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbo_trangThaiItemStateChanged

    private void btn_huy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huy1ActionPerformed
        // TODO add your handling code here:
        readForm();
        Integer rs = donHangService.updateDH(dh);
        if (rs != null) {
            JOptionPane.showMessageDialog(null, "Lưu thông tin đơn hàng thành công");
            loadDataToDH();
            newForm();
        }
    }//GEN-LAST:event_btn_huy1ActionPerformed

    private void txt_khachtraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_khachtraMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_khachtraMouseReleased

    private void cbo_trangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trangThaiActionPerformed
        // TODO add your handling code here:
        trangThai = cbo_trangThai.getSelectedItem().equals("Chờ thanh toán") ? 0 : 1;
        loadDataToDH();
    }//GEN-LAST:event_cbo_trangThaiActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        page++;
        phanTrang.setText(String.valueOf(page));
        loadDataToSP();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (page > 1) {
            page--;
        }
        phanTrang.setText(String.valueOf(page));
        loadDataToSP();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        float tienDua = Float.valueOf(txt_khachtra.getText());
        float tienTra = tienDua - dh.getTongTien();
        if (tienTra < 0) {
            JOptionPane.showMessageDialog(null, "Không dủ tiền thanh toán");
            return;
        }
        txt_tralai.setText(String.valueOf(tienTra));
    }//GEN-LAST:event_jButton11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ThanhToan;
    private javax.swing.JButton btn_giaoHang;
    private javax.swing.JButton btn_hoanThanh;
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_huy1;
    private javax.swing.JButton btn_thanhToan;
    private javax.swing.JComboBox<String> cbo_httt;
    private javax.swing.JComboBox<String> cbo_loaiDH;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lbldongho;
    private javax.swing.JPanel panelhd;
    private javax.swing.JLabel phanTrang;
    private javax.swing.JPanel qrcode;
    private javax.swing.JTable tbl_dh;
    private javax.swing.JTable tbl_dhct;
    private javax.swing.JTable tbl_sp;
    private javax.swing.JCheckBox thanhToanDatHang;
    private javax.swing.JTextArea txt_diaChi;
    private javax.swing.JTextField txt_diem;
    private javax.swing.JLabel txt_giaGiam;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_khachtra;
    private javax.swing.JLabel txt_manv;
    private javax.swing.JTextField txt_phiship;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JLabel txt_tienhang;
    private javax.swing.JTextField txt_tk;
    private javax.swing.JLabel txt_tongtien;
    private javax.swing.JLabel txt_tralai;
    // End of variables declaration//GEN-END:variables

    private void loadDataToSP() {
        spctmodel.setRowCount(0);
        kmlist.removeAll(kmlist);
        spctlist = sanPhamChiTietService.pagingByTen(page, 10, ten, "1");
        int vitri = 1;
        if (page != 1) {
            vitri = (page - 1) * 10 + 1;
        }
        for (SanPhamChiTiet spct : spctlist) {
            SanPham sp = sanPhamChiTietService.searchByIdSP(spct.getMaSanPham());
            KhuyenMai km = khuyenMaiService.searchKMofSP(spct.getMaSanPhamChiTiet());
            float giaGiam = 0;
            if (km != null) {
                kmlist.add(km);
                if (km.getDonViGiam().equalsIgnoreCase("vnd")) {
                    giaGiam = spct.getDonGia() - km.getGiatriGiam();
                } else {
                    giaGiam = spct.getDonGia() * (100 - km.getGiatriGiam()) / 100;
                }
            } else {
                giaGiam = spct.getDonGia();
                KhuyenMai kmc = new KhuyenMai("", "", "", "", "", 1, "", 0);
                kmlist.add(kmc);
            }
            DecimalFormat decimalFormat = new DecimalFormat("#,### VND");
            String formattedAmount = decimalFormat.format(giaGiam);
            String formattedAmount1 = decimalFormat.format(spct.getDonGia());
            spctmodel.addRow(new Object[]{
                vitri, sp.getTenSanPham(), donViTinhService.findByID(spct.getMaDonViTinh()).toString(),
                spct.getKhoiLuong() + " " + spct.getDonViTinhKhoiLuong(), formattedAmount1,
                spct.getSoLuong(), km == null ? "" : km.getGiatriGiam() + " " + km.getDonViGiam(),
                formattedAmount
            });
            vitri++;
        }
    }

    private void loadDataToDHCT(int maDonHang) {
        dhctmodel.setRowCount(0);
        dhctlist = donHangService.getAllDHCT(maDonHang);
        int vitri = 1;
        DecimalFormat decimalFormat = new DecimalFormat("#,### VND");
        for (DonHangChiTiet dhct : dhctlist) {
            SanPhamChiTiet spct = sanPhamChiTietService.searchByIdSPCT(dhct.getMaSanPhamChiTiet());
            SanPham sp = sanPhamChiTietService.searchByIdSP(spct.getMaSanPham());
            String formattedAmount = decimalFormat.format(dhct.getGiaGiam());
            String formattedAmount2 = decimalFormat.format(dhct.getDonGia());
            String formattedAmount1 = decimalFormat.format(dhct.getTongGia());
            dhctmodel.addRow(new Object[]{
                vitri, sp.getTenSanPham(), donViTinhService.findByID(spct.getMaDonViTinh()).toString(),
                spct.getKhoiLuong() + " " + spct.getDonViTinhKhoiLuong(), formattedAmount2, formattedAmount, dhct.getSoLuong(),
                formattedAmount1
            });
            vitri++;
        }
    }

    private void loadDataToDH() {
        dhmodel.setRowCount(0);
        dhlist = donHangService.getAllDH(trangThai, loaiDonHang);
        int vitri = 1;
        DecimalFormat decimalFormat = new DecimalFormat("#,### VND");
        for (DonHang dh : dhlist) {
            String formattedAmount = decimalFormat.format(dh.getTongTien());
            dhmodel.addRow(new Object[]{
                vitri, dh.getMaNhanVien(), formattedAmount,
                dh.isLoaiDonHang() == 0 ? "Chờ lấy hàng" : dh.isLoaiDonHang() == 1 ? "Đang giao" : "Tại quầy",
                dh.isTrangThai() == 1 ? "Đã thanh toán" : "Chờ thanh toán"
            });
            vitri++;
        }
    }

    private void themSPtoDHCT() {
        String slString = JOptionPane.showInputDialog("Mời nhập số lượng");
        if (slString == null) {
            return;
        }
        if (!slString.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Sai kiểu dữ liệu");
            return;
        }
        int sl = Integer.valueOf(slString);
        if (sl > spct.getSoLuong()) {
            JOptionPane.showMessageDialog(null, "Không dủ số lượng sản phẩm");
            return;
        }
        DonHangChiTiet dhct = donHangService.searchSPCTFromDH(maDH, spct.getMaSanPhamChiTiet());
        Integer rs;
        if (dhct != null) {
            dhct.setSoLuong(dhct.getSoLuong() + sl);
            rs = donHangService.updateDHCT(dhct);
        } else {
            rs = insertDHCT(sl);
        }
        if (rs != null) {
            loadDataToDHCT(maDH);
            spct.setSoLuong(spct.getSoLuong() - sl);
            SanPham sp = new SanPham();
            sanPhamChiTietService.updateSPCT(sp, spct);
            loadDataToSP();
            System.out.println(dh.getMaKhachHang());
            System.out.println(dh.getMaHHTT());
            dh.setMaKhachHang(0);
            donHangService.updateDH(dh);
            loadDataToDH();
        } else {
            JOptionPane.showMessageDialog(null, "Thêm thất bại");
        }
    }

    public Integer insertDHCT(int sl) {
        float giaGiam = 0;
        dhct = new DonHangChiTiet();
        dhct.setSoLuong(sl);
        dhct.setMaSanPhamChiTiet(spct.getMaSanPhamChiTiet());
        dhct.setMaDonHang(maDH);
        dhct.setDonGia(spct.getDonGia());
        if (km != null) {
            dhct.setGiaTriGiam(km.getGiatriGiam());
            dhct.setDonViGiam(km.getDonViGiam());
            if (km.getDonViGiam().equalsIgnoreCase("vnd")) {
                giaGiam = spct.getDonGia() - km.getGiatriGiam();
            } else if (km.getDonViGiam().equalsIgnoreCase("%")) {
                giaGiam = spct.getDonGia() * (100 - km.getGiatriGiam()) / 100;
            }
            if (giaGiam == 0) {
                giaGiam = spct.getDonGia();
            }
        }
        if (giaGiam == 0) {
            giaGiam = dhct.getDonGia();
        }
        dhct.setGiaGiam(giaGiam);
        dhct.setTongGia(giaGiam * sl);
        dhct.setTrangThai(true);
        return donHangService.insertDHCT(dhct);
    }

    public void thanhToan() {
        tienGiam = Float.valueOf(txt_diem.getText()) * 1000;
        if (dh.getTienHang() + phiShip >= tienGiam) {
            txt_diem.setText("0");
            String formattedAmount = decimalFormat.format(tienGiam);
            txt_giaGiam.setText(formattedAmount);
            tongTien = dh.getTienHang() + phiShip - tienGiam;
            formattedAmount = decimalFormat.format(tongTien);
            txt_tongtien.setText(formattedAmount);
        } else {
            tienGiam = dh.getTienHang() + phiShip;
            String formattedAmount = decimalFormat.format(tienGiam);
            txt_giaGiam.setText(formattedAmount);
            tongTien = 0;
            txt_diem.setText(String.valueOf(Math.round((tienGiam - dh.getTienHang() - phiShip) / 1000)));
            txt_tongtien.setText(String.valueOf(0));
        }
    }

    public void readForm() {
        dh.setTienGiam(tienGiam);
        dh.setTongTien(tongTien);
        dh.setDiaChi(txt_diaChi.getText());
        dh.setDienThoai(txt_sdt.getText());
        dh.setPhiKhac(phiShip);
        dh.setMaHHTT(cbo_httt.getSelectedItem().equals("Tiền mặt") ? 1 : 2);
    }

    public void newForm() {
        txt_giaGiam.setText("0");
        txt_tongtien.setText("0");
        txt_diaChi.setText("");
        txt_sdt.setText("");
        txt_phiship.setText("0");
        txt_hoten.setText("");
        txt_diem.setText("0");
        txt_khachtra.setText("0");
        txt_tralai.setText("0");
        phiShip = 0;
        tienGiam = 0;
        tongTien = 0;
    }

    public void tichDiem() {
        if (dh.getMaKhachHang() != 0) {
            System.out.println("tich điểm");
            int tichDiem = Integer.valueOf(txt_diem.getText());
            if (dh.isTrangThai() == 1) {
                tichDiem += Math.floor(dh.getTongTien() / 1000 * 0.05);
            }
            KhachHang kh = khachHangService.paging(1, 1, txt_sdt.getText(), "").get(0);
            kh.setDiem(tichDiem);
            khachHangService.update(kh);
        }
    }

    @Override
    public void run() {
        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            Result result = null;
            BufferedImage image = null;

            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    continue;
                }
            }

            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException e) {
                //No result...
            }

            if (result != null) {
                System.out.println(result.getText());
                spct = sanPhamChiTietService.searchByIdBarcode(result.getText());
                if (!spct.getTrangThai()) {
                    JOptionPane.showMessageDialog(null, "Sản phẩm đã ngừng kinh doanh");
                    return;
                }
                km = khuyenMaiService.searchKMofSP(spct.getMaSanPhamChiTiet());
                themSPtoDHCT();
            }
        } while (true);
    }

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }

    private void dongHo() {
        TimerTask timerTask = new TimerTask() {
            @Override
            public void run() {
                lbldongho.setText(XDate.toString(XDate.now(), "dd MMM yyyy HH:mm:ss"));
            }
        };
        int period = 1000;
        Timer timer = new Timer("Dong ho");
        timer.schedule(timerTask, 0, period);
    }

    public void exportExcel(ArrayList<DonHangChiTiet> dhctList) {
        try {
            // Tạo một workbook mới
            String defaultFilePath = "src\\utilities\\HoaDon\\";

            Workbook workbook = new XSSFWorkbook();

            // Tạo một trang tính mới
            Sheet sheet = workbook.createSheet("Data");

            // Dữ liệu mẫu từ ArrayList
            ArrayList<Object[]> dataList = new ArrayList<>();

            // Ghi dữ liệu vào trang tính
            int rowNum = 0;
            Row row = sheet.createRow(rowNum++);
            row.createCell(5).setCellValue("Hóa đơn");
            rowNum++;
            row = sheet.createRow(rowNum++);
            row.createCell(1).setCellValue("Tên sản phẩm");
            row.createCell(2).setCellValue("Khối lượng");
            row.createCell(3).setCellValue("Đơn giá");
            row.createCell(4).setCellValue("Giá giảm");
            row.createCell(5).setCellValue("Số lượng");
            row.createCell(6).setCellValue("Thành tiền");
            rowNum++;
            for (DonHangChiTiet dhct : dhctList) {
                SanPhamChiTiet spct = sanPhamChiTietService.searchByIdSPCT(dhct.getMaSanPhamChiTiet());
                SanPham sp = sanPhamChiTietService.searchByIdSP(spct.getMaSanPham());
                row = sheet.createRow(rowNum++);
                row.createCell(1).setCellValue(sp.getTenSanPham());
                row.createCell(2).setCellValue(spct.getKhoiLuong() + spct.getDonViTinhKhoiLuong());
                row.createCell(3).setCellValue(dhct.getDonGia());
                row.createCell(4).setCellValue(dhct.getGiaGiam());
                row.createCell(5).setCellValue(dhct.getSoLuong());
                row.createCell(6).setCellValue(dhct.getTongGia());
            }

            for (int i = 0; i < sheet.getRow(0).getPhysicalNumberOfCells(); i++) {
                sheet.autoSizeColumn(i);
            }

            try (FileOutputStream outputStream = new FileOutputStream( ".xlsx")) {
                workbook.write(outputStream);
            }

            // Đóng workbook
            workbook.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
